TFF-i2p: WIP

diff --git a/macos/build/build b/macos/build/build
--- a/macos/build/build
+++ b/macos/build/build
@@ -10,12 +10,10 @@ if [ "$dir" = "$0" ]; then
 fi
 cd $dir
 
-arch=$(uname -m)
-language=$(osascript -e 'user locale of (get system info)' | sed -e 's/_/-/g')
-version="102.3.0esr"
+version="32.5"
 i2pdversion="2.43.0"
-
-ftpmirror="https://ftp.mozilla.org/pub/firefox/releases/${version}"
+mpprefix="/opt/local"
+sourceforgemirror="https://sourceforge.net/projects/tenfourfox/files"
 
 curlfind=$(which curl)
 if [ -z $curlfind ]; then
@@ -23,39 +21,18 @@ if [ -z $curlfind ]; then
 	exit 1
 fi
 
-# We support only English (US) and Russian
-if [ "$language" != "ru" ]; then
-	language="en-US"
-fi
+echo "This script is preparing TenFourFox $version for use with I2Pd"
 
-echo "This script is preparing Firefox $version for use with I2Pd"
+file="TenFourFoxG5-FPR${version}.app.zip"
+filepath="fpr${version}/${file}"
 
-file="Firefox ${version}.dmg"
-filepath="mac/${language}/${file}"
+echo "Downloading TenFourFox..."
 
-echo "Downloading $application..."
-
-tmpfilepath=$(echo $filepath | sed 's/ /%20/g')
-curl -L -f -# -o "${file}" "${ftpmirror}/${tmpfilepath}"
-if [ $? -ne 0 ]; then # Not found error, trying to cut language variable
-	echo "[TRY 2] I'll try downloading Firefox with shorter language code"
-	language=$(echo $language | cut -c-2)
-	# re-create variable with cutted lang
-	filepath="mac/$language/$file"
-	tmpfilepath=$(echo $filepath | sed 's/ /%20/g')
-	curl -L -f -# -o "${file}" "${ftpmirror}/${tmpfilepath}"
-	if [ $? -ne 0 ]; then # Not found error, trying to download english version
-		echo "[TRY 3] I'll try downloading Firefox with the English language code"
-		language="en_US"
-		# re-create lang variable
-		filepath="mac/$language/$file"
-		tmpfilepath=$(echo $filepath | sed 's/ /%20/g')
-		curl -L -f -# -o "${file}" "${ftpmirror}/${tmpfilepath}"
-		if [ $? -ne 0 ]; then # After that i can say only that user haven't internet connection
-			echo "[Error] Can't download file. Check your internet connectivity."
-			exit 1
-		fi
-	fi
+tmpfilepath=$(echo $filepath)
+curl -L -f -# -o "${file}" "${sourceforgemirror}/${tmpfilepath}"
+if [ $? -ne 0 ]; then # Not found error
+	echo "[Error] Can't download file. Check your internet connectivity."
+	exit 1
 fi
 
 if [ ! -f "$file" ]; then
@@ -63,63 +40,33 @@ if [ ! -f "$file" ]; then
 	exit 1
 fi
 
-echo "Downloading checksum file and checking SHA512 checksum"
-curl -L -f -# -O "${ftpmirror}/SHA512SUMS"
-recv_sum=$(grep "$filepath" SHA512SUMS | cut -c-128)
-file_sum=$(shasum -a 512 "$file" | cut -c-128)
-if [ $recv_sum != $file_sum ]; then
-	echo "[Error] File checksum failed!"
-	exit 1
-else
-	echo "Checksum correct."
-	rm SHA512SUMS
-fi
-
-echo "Attaching image and copying files..."
-hdiutil attach "$file"
-cp -r /Volumes/Firefox/Firefox.app ../FirefoxESR.app
+echo "Extracting files..."
+unzip "$file" -d ../
 mkdir ../data
 
-echo "Detaching image and removing image file..."
-hdiutil detach /Volumes/Firefox
+echo "Removing archive file..."
 rm "$file"
 
-## TODO: check on linux before make that changes
 # Deleting some not needed files
-rm -r ../FirefoxESR.app/Contents/Library
-rm -r ../FirefoxESR.app/Contents/MacOS/crashreporter.app
-rm ../FirefoxESR.app/Contents/MacOS/pingsender
-rm -r ../FirefoxESR.app/Contents/MacOS/updater.app
-rm ../FirefoxESR.app/Contents/Resources/browser/crashreporter-override.ini
-rm ../FirefoxESR.app/Contents/Resources/browser/features/formautofill@mozilla.org.xpi
-rm ../FirefoxESR.app/Contents/Resources/browser/features/screenshots@mozilla.org.xpi
-rm ../FirefoxESR.app/Contents/Resources/precomplete
-rm ../FirefoxESR.app/Contents/Resources/removed-files
-rm ../FirefoxESR.app/Contents/Resources/update*
-# And edit some places
-sed -i '' -e "s/Enabled=1/Enabled=0/g" "../FirefoxESR.app/Contents/Resources/application.ini"
-sed -i '' -e "s/ServerURL=.*/ServerURL=-/" "../FirefoxESR.app/Contents/Resources/application.ini"
+rm ../TenFourFoxG5.app/Contents/Resources/update*
+# This file not used in TFF:
+# sed -i '' -e "s/Enabled=1/Enabled=0/g" "../FirefoxESR.app/Contents/Resources/application.ini"
+# sed -i '' -e "s/ServerURL=.*/ServerURL=-/" "../FirefoxESR.app/Contents/Resources/application.ini"
 # Done!
 
 echo "Downloading language packs..."
-mkdir ../FirefoxESR.app/Contents/Resources/browser/extensions
-curl -L -f -# -o ../FirefoxESR.app/Contents/Resources/browser/extensions/langpack-ru@firefox.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3971589/russian_ru_language_pack-102.0.1buildid20220705.093820.xpi
-curl -L -f -# -o ../FirefoxESR.app/Contents/Resources/browser/extensions/ruspell-wiktionary@addons.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3997957/2696307-1.41.xpi
-curl -L -f -# -o ../FirefoxESR.app/Contents/Resources/browser/extensions/langpack-en-US@firefox.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3971625/english_us_language_pack-102.0.1buildid20220705.093820.xpi
-curl -L -f -# -o ../FirefoxESR.app/Contents/Resources/browser/extensions/en-US@dictionaries.addons.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3893473/us_english_dictionary-91.0.xpi
+# Already exists:
+mkdir ../TenFourFoxG5.app/Contents/Resources/browser/extensions
+curl -L -f -# -o ../TenFourFoxG5.app/Contents/Resources/browser/extensions/langpack-en-US@firefox.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3971625/english_us_language_pack-102.0.1buildid20220705.093820.xpi
+curl -L -f -# -o ../TenFourFoxG5.app/Contents/Resources/browser/extensions/en-US@dictionaries.addons.mozilla.org.xpi https://addons.mozilla.org/firefox/downloads/file/3893473/us_english_dictionary-91.0.xpi
 
 echo "Downloading NoScript extension..."
-curl -L -f -# -o ../FirefoxESR.app/Contents/Resources/browser/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi https://addons.mozilla.org/firefox/downloads/file/4002416/noscript-11.4.11.xpi
+curl -L -f -# -o ../TenFourFoxG5.app/Contents/Resources/browser/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi https://addons.mozilla.org/firefox/downloads/file/4002416/noscript-11.4.11.xpi
 
 echo "Adding standard configs..."
-cp -r preferences/* ../FirefoxESR.app/Contents/Resources/
+cp -r preferences/* ../TenFourFoxG5.app/Contents/Resources/
 cp -r profile/* ../data/
-
-if [ "$language" = "ru" ]; then
-	cp -r profile-ru/* ../data/
-else
-	cp -r profile-en/* ../data/
-fi
+cp -r profile-en/* ../data/
 
 echo '#!/bin/sh' > "../i2pdbrowser-portable"
 echo 'dir=${0%/*}' >> "../i2pdbrowser-portable"
@@ -127,16 +74,19 @@ echo 'if [ "$dir" = "$0" ]; then' >> "../i2pdbrowser-portable"
 echo '  dir="."' >> "../i2pdbrowser-portable"
 echo 'fi' >> "../i2pdbrowser-portable"
 echo 'cd $dir' >> "../i2pdbrowser-portable"
-echo 'FirefoxESR.app/Contents/MacOS/firefox -profile data -no-remote' >> "../i2pdbrowser-portable"
+echo 'TenFourFoxG5.app/Contents/MacOS/firefox -profile data -no-remote' >> "../i2pdbrowser-portable"
 
 chmod +x "../i2pdbrowser-portable"
 
-echo "Downloading i2pd..."
-curl -L -f -# -O "https://github.com/PurpleI2P/i2pd/releases/download/${i2pdversion}/i2pd_${i2pdversion}_osx.tar.gz"
+echo "Linking i2pd..."
+
+if [ ! -f "${mpprefix}/bin/i2pd" ]; then
+	echo "[Error] Can't find i2pd in MacPorts prefix. Please make sure it is installed."
+	exit 1
+fi
+
 mkdir ../i2pd
-tar xfz i2pd_${i2pdversion}_osx.tar.gz -C ../i2pd
-mv ../i2pd/i2pd ../i2pd/i2pd-osx
 cp -rf i2pd/* ../i2pd
-rm "i2pd_${i2pdversion}_osx.tar.gz"
+chmod +x "../i2pd/i2pd"
 
 echo "... finished"
